# Usa una imagen oficial de Python
FROM python:3.12-slim

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el script Python al contenedor
COPY etlejemplo.py .

# Instala las dependencias
RUN pip install --no-cache-dir requests beautifulsoup4 pandas plotly

# Ejecuta el script
CMD ["python", "etlejemplo.py"]